fails:Exception#exception returns self when passed self as an argument
